version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      # - '80:80'
      - '10080:10080'
      # - '443:443'
      - '10443:10443'
      # - '22:22'
      - '10022:10022'
    volumes:
      - /d/Projects/Devops/gitlab/config:/etc/gitlab
      - /d/Projects/Devops/gitlab/logs:/var/log/gitlab
      - /d/Projects/Devops/gitlab/data:/var/opt/gitlab
    shm_size: '256m'